/**************************************************************************
 *                                                                        *
 *  File:        ActiveUserControl.Designer.cs                            *
 *  Copyright:   (c) 2024, Marco Galatanu                                 *
 *  E-mail:      marco-ionut.galatanu@student.tuiasi.ro                   *
 *  Description: Code generated by Visual Studio for the active user      *
 *  control view                                                          *
 *                                                                        *
 *  This program is free software; you can redistribute it and/or modify  *
 *  it under the terms of the GNU General Public License as published by  *
 *  the Free Software Foundation. This program is distributed in the      *
 *  hope that it will be useful, but WITHOUT ANY WARRANTY; without even   *
 *  the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR   *
 *  PURPOSE. See the GNU General Public License for more details.         *
 *                                                                        *
 **************************************************************************/
using System;
using System.Drawing;
using System.Windows.Forms;

namespace ChatApp
{
    partial class ActiveUserControl
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.ListBox listBoxActiveUsers;
        private System.Windows.Forms.Button buttonActiveUsersExit;
        private System.Windows.Forms.Button buttonChatWithActiveUser;
        private System.Windows.Forms.Label labelLoggedUsername;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.listBoxActiveUsers = new System.Windows.Forms.ListBox();
            this.buttonActiveUsersExit = new System.Windows.Forms.Button();
            this.buttonChatWithActiveUser = new System.Windows.Forms.Button();
            this.labelLoggedUsername = new System.Windows.Forms.Label();
            this.buttonActiveUserHelp = new System.Windows.Forms.Button();
            this.SuspendLayout();
            // 
            // listBoxActiveUsers
            // 
            this.listBoxActiveUsers.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.listBoxActiveUsers.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.listBoxActiveUsers.ForeColor = System.Drawing.Color.White;
            this.listBoxActiveUsers.FormattingEnabled = true;
            this.listBoxActiveUsers.ItemHeight = 17;
            this.listBoxActiveUsers.Location = new System.Drawing.Point(54, 50);
            this.listBoxActiveUsers.Name = "listBoxActiveUsers";
            this.listBoxActiveUsers.Size = new System.Drawing.Size(693, 276);
            this.listBoxActiveUsers.TabIndex = 0;
            this.listBoxActiveUsers.SelectedIndexChanged += new System.EventHandler(this.listBoxActiveUsers_SelectedIndexChanged);
            // 
            // buttonActiveUsersExit
            // 
            this.buttonActiveUsersExit.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.buttonActiveUsersExit.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.buttonActiveUsersExit.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.buttonActiveUsersExit.ForeColor = System.Drawing.Color.White;
            this.buttonActiveUsersExit.Location = new System.Drawing.Point(363, 388);
            this.buttonActiveUsersExit.Name = "buttonActiveUsersExit";
            this.buttonActiveUsersExit.Size = new System.Drawing.Size(75, 33);
            this.buttonActiveUsersExit.TabIndex = 1;
            this.buttonActiveUsersExit.Text = "Exit";
            this.buttonActiveUsersExit.UseVisualStyleBackColor = false;
            this.buttonActiveUsersExit.Click += new System.EventHandler(this.buttonActiveUsersExit_Click);
            // 
            // buttonChatWithActiveUser
            // 
            this.buttonChatWithActiveUser.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.buttonChatWithActiveUser.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.buttonChatWithActiveUser.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.buttonChatWithActiveUser.ForeColor = System.Drawing.Color.White;
            this.buttonChatWithActiveUser.Location = new System.Drawing.Point(363, 350);
            this.buttonChatWithActiveUser.Name = "buttonChatWithActiveUser";
            this.buttonChatWithActiveUser.Size = new System.Drawing.Size(75, 33);
            this.buttonChatWithActiveUser.TabIndex = 2;
            this.buttonChatWithActiveUser.Text = "Chat";
            this.buttonChatWithActiveUser.UseVisualStyleBackColor = false;
            this.buttonChatWithActiveUser.Click += new System.EventHandler(this.buttonChatWithActiveUser_Click);
            // 
            // labelLoggedUsername
            // 
            this.labelLoggedUsername.AutoSize = true;
            this.labelLoggedUsername.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.labelLoggedUsername.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;
            this.labelLoggedUsername.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.labelLoggedUsername.ForeColor = System.Drawing.Color.White;
            this.labelLoggedUsername.Location = new System.Drawing.Point(52, 20);
            this.labelLoggedUsername.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.labelLoggedUsername.Name = "labelLoggedUsername";
            this.labelLoggedUsername.Size = new System.Drawing.Size(116, 23);
            this.labelLoggedUsername.TabIndex = 3;
            this.labelLoggedUsername.Text = "labelUsername";
            // 
            // buttonActiveUserHelp
            // 
            this.buttonActiveUserHelp.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.buttonActiveUserHelp.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.buttonActiveUserHelp.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.buttonActiveUserHelp.ForeColor = System.Drawing.Color.White;
            this.buttonActiveUserHelp.Location = new System.Drawing.Point(722, 3);
            this.buttonActiveUserHelp.Name = "buttonActiveUserHelp";
            this.buttonActiveUserHelp.Size = new System.Drawing.Size(75, 33);
            this.buttonActiveUserHelp.TabIndex = 4;
            this.buttonActiveUserHelp.Text = "Help";
            this.buttonActiveUserHelp.UseVisualStyleBackColor = false;
            this.buttonActiveUserHelp.Click += new System.EventHandler(this.buttonActiveUserHelp_Click);
            // 
            // ActiveUserControl
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.Black;
            this.BackgroundImage = global::ChatApp.Properties.Resources._68747470733a2f2f7765622e77686174736170702e636f6d2f696d672f62672d636861742d74696c652d6461726b5f61346265353132653731393562366237333364393131306234303866303735642e706e67;
            this.Controls.Add(this.buttonActiveUserHelp);
            this.Controls.Add(this.labelLoggedUsername);
            this.Controls.Add(this.buttonChatWithActiveUser);
            this.Controls.Add(this.buttonActiveUsersExit);
            this.Controls.Add(this.listBoxActiveUsers);
            this.Name = "ActiveUserControl";
            this.Size = new System.Drawing.Size(800, 450);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        private Button buttonActiveUserHelp;
    }
}
